name: Build QAMP

on:
  push:
    branches: [ "main" ] # Запускать при каждом пуше в ветку main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
      - 'changelog.txt'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest # Собираем именно на Windows, так как это WPF

    steps:
    - uses: actions/checkout@v4 # Скачиваем твой код

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore # Скачиваем NuGet-пакеты (TagLib, NAudio и т.д.)

    - name: Build
      run: dotnet build --configuration Release --no-restore